server:
  port: 2019
  
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    initialization-mode: always     
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
